        DB 5 ;00
        DB 5 ;01
        DB 5 ;02
        DB 5 ;03
        DB 5 ;04
        DB 5 ;05
        DB 5 ;06
        DB 5 ;07
        DB 6 ;08
        DB 6 ;09
        DB 6 ;0a
        DB 6 ;0b
        DB 5 ;0c
        DB 5 ;0d
        DB 5 ;0e
        DB 5 ;0f

        DB 5 ;10
        DB 5 ;11
        DB 5 ;12
        DB 5 ;13
        DB 5 ;14
        DB 5 ;15
        DB 5 ;16
        DB 5 ;17
        DB 5 ;18
        DB 5 ;19
        DB 5 ;1a
        DB 5 ;1b
        DB 5 ;1c
        DB 5 ;1d
        DB 5 ;1e
        DB 5 ;11

        DB 3 ;sp;ace
        DB 1 ;!
        DB 3 ;"
        DB 5 ;#
        DB 4  ;$
        DB 5 ;%
        DB 5 ;&
        DB 2 ;'
        DB 2 ;(
        DB 2 ;)
        DB 5 ;*
        DB 5 ;+
        DB 2 ;,
        DB 3 ;-
        DB 1 ;.
        DB 3 ;/

        DB 4 ;0
        DB 2 ;1
        DB 4 ;2
        DB 4 ;3
        DB 4 ;4
        DB 4 ;5
        DB 4 ;6
        DB 4 ;7
        DB 4 ;8
        DB 4 ;9
        DB 1 ;:
        DB 2 ;;
        DB 3 ;<
        DB 3 ;=
        DB 3 ;>
        DB 4 ;?

        DB 7 ;@
        DB 4 ;A
        DB 4 ;B
        DB 4 ;C
        DB 4 ;D
        DB 4 ;E
        DB 4 ;F
        DB 4 ;G
        DB 4 ;H
        DB 3 ;I
        DB 3 ;J
        DB 4 ;K
        DB 4 ;L
        DB 5 ;M
        DB 4 ;N
        DB 4 ;O

        DB 4 ;P
        DB 4 ;Q
        DB 4 ;R
        DB 4 ;S
        DB 5 ;T
        DB 4 ;U
        DB 5 ;V
        DB 5 ;W
        DB 5 ;X
        DB 5 ;Y
        DB 4 ;Z
        DB 2 ;[
        DB 3 ;\
        DB 2 ;]
        DB 5 ;^
        DB 4 ;_

        DB 2 ;backtick
        DB 4 ;a
        DB 4 ;b
        DB 3 ;c
        DB 4 ;d
        DB 4 ;e
        DB 2 ;f
        DB 4 ;g
        DB 4 ;h
        DB 1 ;i
        DB 2 ;j
        DB 4 ;k
        DB 2 ;l
        DB 5 ;m
        DB 4 ;n
        DB 4 ;o

        DB 4 ;p
        DB 4 ;q
        DB 3 ;r
        DB 3 ;s
        DB 2 ;t
        DB 4 ;u
        DB 4 ;v
        DB 5 ;w
        DB 5 ;x
        DB 4 ;y
        DB 4 ;z
        DB 3 ;{
        DB 1 ;|
        DB 3 ;}
        DB 4 ;~
        DB 4 ;del
