        db 5 ;00
        db 5 ;01
        db 5 ;02
        db 5 ;03
        db 5 ;04
        db 5 ;05
        db 5 ;06
        db 5 ;07
        db 6 ;08
        db 6 ;09
        db 6 ;0a
        db 6 ;0b
        db 5 ;0c
        db 5 ;0d
        db 5 ;0e
        db 5 ;0f

        db 5 ;10
        db 5 ;11
        db 5 ;12
        db 5 ;13
        db 5 ;14
        db 5 ;15
        db 5 ;16
        db 5 ;17
        db 5 ;18
        db 5 ;19
        db 5 ;1a
        db 5 ;1b
        db 5 ;1c
        db 5 ;1d
        db 5 ;1e
        db 5 ;11

        db 3 ;sp;ace
        db 1 ;!
        db 3 ;"
        db 5 ;#
        db 4  ;$
        db 5 ;%
        db 5 ;&
        db 2 ;'
        db 2 ;(
        db 2 ;)
        db 5 ;*
        db 5 ;+
        db 2 ;,
        db 3 ;-
        db 1 ;.
        db 3 ;/

        db 4 ;0
        db 2 ;1
        db 4 ;2
        db 4 ;3
        db 4 ;4
        db 4 ;5
        db 4 ;6
        db 4 ;7
        db 4 ;8
        db 4 ;9
        db 1 ;:
        db 2 ;;
        db 3 ;<
        db 3 ;=
        db 3 ;>
        db 4 ;?

        db 7 ;@
        db 4 ;A
        db 4 ;B
        db 4 ;C
        db 4 ;D
        db 4 ;E
        db 4 ;F
        db 4 ;G
        db 4 ;H
        db 3 ;I
        db 3 ;J
        db 4 ;K
        db 4 ;L
        db 5 ;M
        db 4 ;N
        db 4 ;O

        db 4 ;P
        db 4 ;Q
        db 4 ;R
        db 4 ;S
        db 5 ;T
        db 4 ;U
        db 5 ;V
        db 5 ;W
        db 5 ;X
        db 5 ;Y
        db 4 ;Z
        db 2 ;[
        db 3 ;\
        db 2 ;]
        db 5 ;^
        db 4 ;_

        db 2 ;backtick
        db 4 ;a
        db 4 ;b
        db 3 ;c
        db 4 ;d
        db 4 ;e
        db 2 ;f
        db 4 ;g
        db 4 ;h
        db 1 ;i
        db 2 ;j
        db 4 ;k
        db 2 ;l
        db 5 ;m
        db 4 ;n
        db 4 ;o

        db 4 ;p
        db 4 ;q
        db 3 ;r
        db 3 ;s
        db 2 ;t
        db 4 ;u
        db 4 ;v
        db 5 ;w
        db 5 ;x
        db 4 ;y
        db 4 ;z
        db 3 ;{
        db 1 ;|
        db 3 ;}
        db 4 ;~
        db 4 ;del
